name: CMake with GCC on Windows (MinGW Cache)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - uses: actions/checkout@v4

    # 配置 CMake
    - name: Configure CMake 
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # 编译项目
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # 运行测试
    - name: Run tests
      run: ./build/tests --gtest_color=auto
